# Generated by Django 4.2.29 on 2026-05-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnifiedRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="queued", max_length=24)),
                ("trigger", models.CharField(default="manual", max_length=40)),
                ("input_payload", models.JSONField(default=dict)),
                ("output_payload", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="UnifiedRunStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_key", models.CharField(max_length=80)),
                ("status", models.CharField(default="queued", max_length=24)),
                ("input_payload", models.JSONField(default=dict)),
                ("output_payload", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="runs.unifiedrun")),
            ],
            options={"abstract": False},
        ),
    ]
