# Generated by Django 6.0.5 on 2026-05-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_workflowtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedrun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unifiedrunstep',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
