# Generated by Django 4.2.29 on 2026-05-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCostLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.CharField(blank=True, max_length=80)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('model_name', models.CharField(default='gpt-4.1-mini', max_length=80)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_estimated', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_costs', to='runs.unifiedrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(default='info', max_length=16)),
                ('event_type', models.CharField(max_length=48)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runs.unifiedrun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
