# Generated by Django 4.2.29 on 2026-05-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('role', models.CharField(max_length=120)),
                ('system_prompt', models.TextField()),
                ('model', models.CharField(default='gpt-4.1-mini', max_length=80)),
                ('tools', models.JSONField(default=list)),
                ('channels', models.JSONField(default=list)),
                ('schedule', models.JSONField(default=dict)),
                ('memory_profile', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=list)),
                ('interaction_rules', models.JSONField(default=list)),
                ('guardrails', models.JSONField(default=list)),
                ('limits', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
