# Generated by Django 4.2.29 on 2026-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ingestion', 'Ingestion'), ('memory', 'Memory'), ('risk', 'Risk'), ('trade', 'Trade'), ('research', 'Research'), ('communication', 'Communication'), ('monitoring', 'Monitoring')], default='ingestion', max_length=80)),
                ('capabilities', models.JSONField(default=list)),
                ('config_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
