# Generated by Django 4.2.29 on 2026-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="model",
            field=models.CharField(default="nvidia/nemotron-3-super-120b-a12b:free", max_length=80),
        ),
    ]
