# Generated by Django 4.2.29 on 2026-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_alter_agent_model_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("policy", "Policy"), ("procedure", "Procedure"), ("output", "Output"), ("general", "General")],
                        default="general",
                        max_length=80,
                    ),
                ),
                ("trigger", models.CharField(default="always", max_length=120)),
                ("priority", models.IntegerField(default=100)),
                ("requires_tools", models.JSONField(default=list)),
                ("output_schema", models.CharField(blank=True, max_length=120)),
                ("abort_on_fail", models.BooleanField(default=False)),
                ("markdown", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
    ]
