# Generated by Django 6.0.5 on 2026-05-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(default='internal', max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('avg_price', models.FloatField(default=0.0)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('unrealized_pnl', models.FloatField(default=0.0)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('run_id', models.CharField(blank=True, max_length=36)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('symbol', models.CharField(max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, null=True)),
                ('broker', models.CharField(default='upstox', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('filled', 'Filled'), ('failed', 'Failed'), ('dry_run', 'Dry Run')], default='pending', max_length=20)),
                ('broker_response', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('symbol', models.CharField(default='NIFTY50', max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('option_side', models.CharField(max_length=20)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('target', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True)),
                ('risk_decision', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(db_index=True, max_length=120)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('key', models.CharField(max_length=120)),
                ('value', models.JSONField(default=dict)),
                ('ttl_minutes', models.IntegerField(default=1440)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('agent_name', 'run_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TradeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('symbol', models.CharField(max_length=20)),
                ('pnl', models.FloatField(default=0.0)),
                ('pnl_pct', models.FloatField(default=0.0)),
                ('exit_reason', models.CharField(blank=True, max_length=80)),
                ('feedback', models.JSONField(default=dict)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='agents.tradeexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='agents.tradeplan'),
        ),
    ]
