# Generated by Django 6.0.5 on 2026-05-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_operational_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
