# Generated by Django 6.0.5 on 2026-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_add_is_system_to_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField(db_index=True)),
                ('scope', models.CharField(choices=[('day', 'Full Day'), ('rolling', 'Rolling 2h')], db_index=True, max_length=20)),
                ('key', models.CharField(choices=[('opening_range', 'Opening Range (high/low/time)'), ('day_trend', 'Day Trend (direction/strength)'), ('support', 'Support Levels'), ('resistance', 'Resistance Levels'), ('vwap', 'VWAP + Bands'), ('key_levels', 'Key Price Levels'), ('news_context', 'News & Sentiment'), ('sector_context', 'FII/DII & Sector Flow'), ('buildup_io', 'Inside/Outside Bar Buildup'), ('buildup_oi', 'Open Interest Buildup'), ('momentum', 'RSI/MACD/Volume Momentum'), ('price_action', 'Candle Pattern / Price Action'), ('support_test', 'Support Level Test'), ('resistance_test', 'Resistance Level Test')], db_index=True, max_length=60)),
                ('value', models.JSONField()),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trade_date', 'scope', 'key', '-created_at'], name='agents_trad_trade_d_13502f_idx')],
            },
        ),
    ]
