# Generated by Django 6.0.5 on 2026-05-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_repair_alert_run_id_column'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.RemoveField(
            model_name='tradeexecution',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tradeoutcome',
            name='execution',
        ),
        migrations.RemoveIndex(
            model_name='tradememory',
            name='agents_trad_trade_d_13502f_idx',
        ),
        migrations.DeleteModel(
            name='TradeMemory',
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agentmemory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('ingestion', 'Ingestion'), ('memory', 'Memory'), ('risk', 'Risk'), ('research', 'Research'), ('communication', 'Communication'), ('monitoring', 'Monitoring')], default='ingestion', max_length=80),
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TradePlan',
        ),
        migrations.DeleteModel(
            name='TradeExecution',
        ),
        migrations.DeleteModel(
            name='TradeOutcome',
        ),
    ]
