# Generated by Django 4.2.29 on 2026-05-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_channel', models.CharField(default='whatsapp', max_length=24)),
                ('external_user_id', models.CharField(max_length=120)),
                ('active_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runs.unifiedrun')),
                ('target_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterAgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=120, unique=True)),
                ('channel', models.CharField(default='internal', max_length=40)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('from_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='agents.agent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='runs.unifiedrun')),
                ('to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='agents.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(max_length=12)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.channelconversation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('summary', models.TextField()),
                ('reviewer', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='runs.unifiedrun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
