# Generated by Django 6.0.5 on 2026-05-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_rebuild_stale_sqlite_run_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channelconversation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interagentmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
